// Code generated by capnpc-go. DO NOT EDIT.

package kvcapnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type BlockMeta capnp.Struct

// BlockMeta_TypeID is the unique identifier for the type BlockMeta.
const BlockMeta_TypeID = 0x9c1c43d8c17225f2

func NewBlockMeta(s *capnp.Segment) (BlockMeta, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7})
	return BlockMeta(st), err
}

func NewRootBlockMeta(s *capnp.Segment) (BlockMeta, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7})
	return BlockMeta(st), err
}

func ReadRootBlockMeta(msg *capnp.Message) (BlockMeta, error) {
	root, err := msg.Root()
	return BlockMeta(root.Struct()), err
}

func (s BlockMeta) String() string {
	str, _ := text.Marshal(0x9c1c43d8c17225f2, capnp.Struct(s))
	return str
}

func (s BlockMeta) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BlockMeta) DecodeFromPtr(p capnp.Ptr) BlockMeta {
	return BlockMeta(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BlockMeta) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BlockMeta) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BlockMeta) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BlockMeta) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BlockMeta) Height() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s BlockMeta) SetHeight(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s BlockMeta) Hash() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BlockMeta) HasHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BlockMeta) HashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BlockMeta) SetHash(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BlockMeta) ParentHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BlockMeta) HasParentHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BlockMeta) ParentHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BlockMeta) SetParentHash(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s BlockMeta) StateRoot() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s BlockMeta) HasStateRoot() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s BlockMeta) StateRootBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s BlockMeta) SetStateRoot(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s BlockMeta) Miner() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s BlockMeta) HasMiner() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s BlockMeta) MinerBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s BlockMeta) SetMiner(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s BlockMeta) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s BlockMeta) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s BlockMeta) Size() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s BlockMeta) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s BlockMeta) GasLimit() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s BlockMeta) SetGasLimit(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s BlockMeta) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s BlockMeta) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s BlockMeta) EthTxCount() int32 {
	return int32(capnp.Struct(s).Uint32(40))
}

func (s BlockMeta) SetEthTxCount(v int32) {
	capnp.Struct(s).SetUint32(40, uint32(v))
}

func (s BlockMeta) TxCount() int32 {
	return int32(capnp.Struct(s).Uint32(44))
}

func (s BlockMeta) SetTxCount(v int32) {
	capnp.Struct(s).SetUint32(44, uint32(v))
}

func (s BlockMeta) Bloom() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s BlockMeta) HasBloom() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s BlockMeta) BloomBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s BlockMeta) SetBloom(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s BlockMeta) TransactionsRoot() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s BlockMeta) HasTransactionsRoot() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s BlockMeta) TransactionsRootBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s BlockMeta) SetTransactionsRoot(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s BlockMeta) BaseFee() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s BlockMeta) HasBaseFee() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s BlockMeta) BaseFeeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s BlockMeta) SetBaseFee(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s BlockMeta) VirtualizedCosmosEvents() bool {
	return capnp.Struct(s).Bit(384)
}

func (s BlockMeta) SetVirtualizedCosmosEvents(v bool) {
	capnp.Struct(s).SetBit(384, v)
}

// BlockMeta_List is a list of BlockMeta.
type BlockMeta_List = capnp.StructList[BlockMeta]

// NewBlockMeta creates a new list of BlockMeta.
func NewBlockMeta_List(s *capnp.Segment, sz int32) (BlockMeta_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7}, sz)
	return capnp.StructList[BlockMeta](l), err
}

// BlockMeta_Future is a wrapper for a BlockMeta promised by a client call.
type BlockMeta_Future struct{ *capnp.Future }

func (f BlockMeta_Future) Struct() (BlockMeta, error) {
	p, err := f.Future.Ptr()
	return BlockMeta(p.Struct()), err
}

type Log capnp.Struct

// Log_TypeID is the unique identifier for the type Log.
const Log_TypeID = 0x988b382a961e2d7b

func NewLog(s *capnp.Segment) (Log, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return Log(st), err
}

func NewRootLog(s *capnp.Segment) (Log, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6})
	return Log(st), err
}

func ReadRootLog(msg *capnp.Message) (Log, error) {
	root, err := msg.Root()
	return Log(root.Struct()), err
}

func (s Log) String() string {
	str, _ := text.Marshal(0x988b382a961e2d7b, capnp.Struct(s))
	return str
}

func (s Log) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Log) DecodeFromPtr(p capnp.Ptr) Log {
	return Log(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Log) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Log) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Log) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Log) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Log) Address() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Log) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Log) SetAddress(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Log) Topics() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.DataList(p.List()), err
}

func (s Log) HasTopics() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Log) SetTopics(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewTopics sets the topics field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s Log) NewTopics(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Log) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Log) HasData() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Log) SetData(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Log) BlockNumber() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Log) SetBlockNumber(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Log) TxHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Log) HasTxHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Log) SetTxHash(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Log) TxIndex() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Log) SetTxIndex(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Log) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Log) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Log) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Log) Index() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Log) SetIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Log) Removed() bool {
	return capnp.Struct(s).Bit(192)
}

func (s Log) SetRemoved(v bool) {
	capnp.Struct(s).SetBit(192, v)
}

func (s Log) Virtual() bool {
	return capnp.Struct(s).Bit(193)
}

func (s Log) SetVirtual(v bool) {
	capnp.Struct(s).SetBit(193, v)
}

func (s Log) CosmosHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s Log) HasCosmosHash() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Log) SetCosmosHash(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

func (s Log) CosmosMsgIndex() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Log) SetCosmosMsgIndex(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Log) CosmosMsgIndexPresent() bool {
	return capnp.Struct(s).Bit(194)
}

func (s Log) SetCosmosMsgIndexPresent(v bool) {
	capnp.Struct(s).SetBit(194, v)
}

// Log_List is a list of Log.
type Log_List = capnp.StructList[Log]

// NewLog creates a new list of Log.
func NewLog_List(s *capnp.Segment, sz int32) (Log_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 6}, sz)
	return capnp.StructList[Log](l), err
}

// Log_Future is a wrapper for a Log promised by a client call.
type Log_Future struct{ *capnp.Future }

func (f Log_Future) Struct() (Log, error) {
	p, err := f.Future.Ptr()
	return Log(p.Struct()), err
}

type LogGroup capnp.Struct

// LogGroup_TypeID is the unique identifier for the type LogGroup.
const LogGroup_TypeID = 0xedc6ec3ead9565fa

func NewLogGroup(s *capnp.Segment) (LogGroup, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LogGroup(st), err
}

func NewRootLogGroup(s *capnp.Segment) (LogGroup, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LogGroup(st), err
}

func ReadRootLogGroup(msg *capnp.Message) (LogGroup, error) {
	root, err := msg.Root()
	return LogGroup(root.Struct()), err
}

func (s LogGroup) String() string {
	str, _ := text.Marshal(0xedc6ec3ead9565fa, capnp.Struct(s))
	return str
}

func (s LogGroup) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LogGroup) DecodeFromPtr(p capnp.Ptr) LogGroup {
	return LogGroup(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LogGroup) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LogGroup) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LogGroup) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LogGroup) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LogGroup) Logs() (Log_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Log_List(p.List()), err
}

func (s LogGroup) HasLogs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LogGroup) SetLogs(v Log_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewLogs sets the logs field to a newly
// allocated Log_List, preferring placement in s's segment.
func (s LogGroup) NewLogs(n int32) (Log_List, error) {
	l, err := NewLog_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Log_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// LogGroup_List is a list of LogGroup.
type LogGroup_List = capnp.StructList[LogGroup]

// NewLogGroup creates a new list of LogGroup.
func NewLogGroup_List(s *capnp.Segment, sz int32) (LogGroup_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[LogGroup](l), err
}

// LogGroup_Future is a wrapper for a LogGroup promised by a client call.
type LogGroup_Future struct{ *capnp.Future }

func (f LogGroup_Future) Struct() (LogGroup, error) {
	p, err := f.Future.Ptr()
	return LogGroup(p.Struct()), err
}

type BlockLogs capnp.Struct

// BlockLogs_TypeID is the unique identifier for the type BlockLogs.
const BlockLogs_TypeID = 0x8754b1c1a667a03c

func NewBlockLogs(s *capnp.Segment) (BlockLogs, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BlockLogs(st), err
}

func NewRootBlockLogs(s *capnp.Segment) (BlockLogs, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BlockLogs(st), err
}

func ReadRootBlockLogs(msg *capnp.Message) (BlockLogs, error) {
	root, err := msg.Root()
	return BlockLogs(root.Struct()), err
}

func (s BlockLogs) String() string {
	str, _ := text.Marshal(0x8754b1c1a667a03c, capnp.Struct(s))
	return str
}

func (s BlockLogs) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BlockLogs) DecodeFromPtr(p capnp.Ptr) BlockLogs {
	return BlockLogs(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BlockLogs) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BlockLogs) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BlockLogs) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BlockLogs) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BlockLogs) Groups() (LogGroup_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return LogGroup_List(p.List()), err
}

func (s BlockLogs) HasGroups() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BlockLogs) SetGroups(v LogGroup_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewGroups sets the groups field to a newly
// allocated LogGroup_List, preferring placement in s's segment.
func (s BlockLogs) NewGroups(n int32) (LogGroup_List, error) {
	l, err := NewLogGroup_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return LogGroup_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// BlockLogs_List is a list of BlockLogs.
type BlockLogs_List = capnp.StructList[BlockLogs]

// NewBlockLogs creates a new list of BlockLogs.
func NewBlockLogs_List(s *capnp.Segment, sz int32) (BlockLogs_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[BlockLogs](l), err
}

// BlockLogs_Future is a wrapper for a BlockLogs promised by a client call.
type BlockLogs_Future struct{ *capnp.Future }

func (f BlockLogs_Future) Struct() (BlockLogs, error) {
	p, err := f.Future.Ptr()
	return BlockLogs(p.Struct()), err
}

type Receipt capnp.Struct

// Receipt_TypeID is the unique identifier for the type Receipt.
const Receipt_TypeID = 0xc136c505d60e82cc

func NewReceipt(s *capnp.Segment) (Receipt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10})
	return Receipt(st), err
}

func NewRootReceipt(s *capnp.Segment) (Receipt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10})
	return Receipt(st), err
}

func ReadRootReceipt(msg *capnp.Message) (Receipt, error) {
	root, err := msg.Root()
	return Receipt(root.Struct()), err
}

func (s Receipt) String() string {
	str, _ := text.Marshal(0xc136c505d60e82cc, capnp.Struct(s))
	return str
}

func (s Receipt) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Receipt) DecodeFromPtr(p capnp.Ptr) Receipt {
	return Receipt(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Receipt) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Receipt) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Receipt) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Receipt) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Receipt) Status() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Receipt) SetStatus(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Receipt) CumulativeGasUsed() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Receipt) SetCumulativeGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Receipt) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Receipt) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Receipt) Reason() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Receipt) HasReason() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Receipt) ReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Receipt) SetReason(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Receipt) VmError() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Receipt) HasVmError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Receipt) VmErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Receipt) SetVmError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Receipt) LogsBloom() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Receipt) HasLogsBloom() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Receipt) SetLogsBloom(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Receipt) Logs() (Log_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Log_List(p.List()), err
}

func (s Receipt) HasLogs() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Receipt) SetLogs(v Log_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewLogs sets the logs field to a newly
// allocated Log_List, preferring placement in s's segment.
func (s Receipt) NewLogs(n int32) (Log_List, error) {
	l, err := NewLog_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Log_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Receipt) TransactionHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Receipt) HasTransactionHash() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Receipt) SetTransactionHash(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Receipt) ContractAddress() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s Receipt) HasContractAddress() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Receipt) SetContractAddress(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

func (s Receipt) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return []byte(p.Data()), err
}

func (s Receipt) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Receipt) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(6, v)
}

func (s Receipt) BlockNumber() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s Receipt) SetBlockNumber(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s Receipt) TransactionIndex() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Receipt) SetTransactionIndex(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Receipt) EffectiveGasPrice() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s Receipt) HasEffectiveGasPrice() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Receipt) SetEffectiveGasPrice(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

func (s Receipt) From() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return []byte(p.Data()), err
}

func (s Receipt) HasFrom() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Receipt) SetFrom(v []byte) error {
	return capnp.Struct(s).SetData(8, v)
}

func (s Receipt) To() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return []byte(p.Data()), err
}

func (s Receipt) HasTo() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Receipt) SetTo(v []byte) error {
	return capnp.Struct(s).SetData(9, v)
}

func (s Receipt) Type() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s Receipt) SetType(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s Receipt) ReasonPresent() bool {
	return capnp.Struct(s).Bit(384)
}

func (s Receipt) SetReasonPresent(v bool) {
	capnp.Struct(s).SetBit(384, v)
}

func (s Receipt) VmErrorPresent() bool {
	return capnp.Struct(s).Bit(385)
}

func (s Receipt) SetVmErrorPresent(v bool) {
	capnp.Struct(s).SetBit(385, v)
}

func (s Receipt) EffectiveGasPricePresent() bool {
	return capnp.Struct(s).Bit(386)
}

func (s Receipt) SetEffectiveGasPricePresent(v bool) {
	capnp.Struct(s).SetBit(386, v)
}

// Receipt_List is a list of Receipt.
type Receipt_List = capnp.StructList[Receipt]

// NewReceipt creates a new list of Receipt.
func NewReceipt_List(s *capnp.Segment, sz int32) (Receipt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10}, sz)
	return capnp.StructList[Receipt](l), err
}

// Receipt_Future is a wrapper for a Receipt promised by a client call.
type Receipt_Future struct{ *capnp.Future }

func (f Receipt_Future) Struct() (Receipt, error) {
	p, err := f.Future.Ptr()
	return Receipt(p.Struct()), err
}

type AccessTuple capnp.Struct

// AccessTuple_TypeID is the unique identifier for the type AccessTuple.
const AccessTuple_TypeID = 0x8dea811504a59d2a

func NewAccessTuple(s *capnp.Segment) (AccessTuple, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return AccessTuple(st), err
}

func NewRootAccessTuple(s *capnp.Segment) (AccessTuple, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return AccessTuple(st), err
}

func ReadRootAccessTuple(msg *capnp.Message) (AccessTuple, error) {
	root, err := msg.Root()
	return AccessTuple(root.Struct()), err
}

func (s AccessTuple) String() string {
	str, _ := text.Marshal(0x8dea811504a59d2a, capnp.Struct(s))
	return str
}

func (s AccessTuple) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccessTuple) DecodeFromPtr(p capnp.Ptr) AccessTuple {
	return AccessTuple(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccessTuple) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccessTuple) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccessTuple) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccessTuple) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccessTuple) Address() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s AccessTuple) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccessTuple) SetAddress(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s AccessTuple) StorageKeys() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.DataList(p.List()), err
}

func (s AccessTuple) HasStorageKeys() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccessTuple) SetStorageKeys(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewStorageKeys sets the storageKeys field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s AccessTuple) NewStorageKeys(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// AccessTuple_List is a list of AccessTuple.
type AccessTuple_List = capnp.StructList[AccessTuple]

// NewAccessTuple creates a new list of AccessTuple.
func NewAccessTuple_List(s *capnp.Segment, sz int32) (AccessTuple_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[AccessTuple](l), err
}

// AccessTuple_Future is a wrapper for a AccessTuple promised by a client call.
type AccessTuple_Future struct{ *capnp.Future }

func (f AccessTuple_Future) Struct() (AccessTuple, error) {
	p, err := f.Future.Ptr()
	return AccessTuple(p.Struct()), err
}

type RPCTransaction capnp.Struct

// RPCTransaction_TypeID is the unique identifier for the type RPCTransaction.
const RPCTransaction_TypeID = 0x9bbe5676024b04c9

func NewRPCTransaction(s *capnp.Segment) (RPCTransaction, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 16})
	return RPCTransaction(st), err
}

func NewRootRPCTransaction(s *capnp.Segment) (RPCTransaction, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 16})
	return RPCTransaction(st), err
}

func ReadRootRPCTransaction(msg *capnp.Message) (RPCTransaction, error) {
	root, err := msg.Root()
	return RPCTransaction(root.Struct()), err
}

func (s RPCTransaction) String() string {
	str, _ := text.Marshal(0x9bbe5676024b04c9, capnp.Struct(s))
	return str
}

func (s RPCTransaction) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCTransaction) DecodeFromPtr(p capnp.Ptr) RPCTransaction {
	return RPCTransaction(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCTransaction) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCTransaction) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCTransaction) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCTransaction) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCTransaction) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCTransaction) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s RPCTransaction) BlockNumber() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasBlockNumber() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCTransaction) SetBlockNumber(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s RPCTransaction) From() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasFrom() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RPCTransaction) SetFrom(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s RPCTransaction) Gas() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s RPCTransaction) SetGas(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s RPCTransaction) GasPrice() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasPrice() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s RPCTransaction) SetGasPrice(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s RPCTransaction) GasFeeCap() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasFeeCap() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s RPCTransaction) SetGasFeeCap(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s RPCTransaction) GasTipCap() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasTipCap() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s RPCTransaction) SetGasTipCap(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

func (s RPCTransaction) Hash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasHash() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s RPCTransaction) SetHash(v []byte) error {
	return capnp.Struct(s).SetData(6, v)
}

func (s RPCTransaction) Input() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasInput() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s RPCTransaction) SetInput(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

func (s RPCTransaction) Nonce() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s RPCTransaction) SetNonce(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s RPCTransaction) To() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasTo() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s RPCTransaction) SetTo(v []byte) error {
	return capnp.Struct(s).SetData(8, v)
}

func (s RPCTransaction) TransactionIndex() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s RPCTransaction) SetTransactionIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s RPCTransaction) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasValue() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s RPCTransaction) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(9, v)
}

func (s RPCTransaction) Type() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s RPCTransaction) SetType(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s RPCTransaction) Accesses() (AccessTuple_List, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return AccessTuple_List(p.List()), err
}

func (s RPCTransaction) HasAccesses() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s RPCTransaction) SetAccesses(v AccessTuple_List) error {
	return capnp.Struct(s).SetPtr(10, v.ToPtr())
}

// NewAccesses sets the accesses field to a newly
// allocated AccessTuple_List, preferring placement in s's segment.
func (s RPCTransaction) NewAccesses(n int32) (AccessTuple_List, error) {
	l, err := NewAccessTuple_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return AccessTuple_List{}, err
	}
	err = capnp.Struct(s).SetPtr(10, l.ToPtr())
	return l, err
}
func (s RPCTransaction) ChainId() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasChainId() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s RPCTransaction) SetChainId(v []byte) error {
	return capnp.Struct(s).SetData(11, v)
}

func (s RPCTransaction) V() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasV() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s RPCTransaction) SetV(v []byte) error {
	return capnp.Struct(s).SetData(12, v)
}

func (s RPCTransaction) R() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasR() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s RPCTransaction) SetR(v []byte) error {
	return capnp.Struct(s).SetData(13, v)
}

func (s RPCTransaction) S() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasS() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s RPCTransaction) SetS(v []byte) error {
	return capnp.Struct(s).SetData(14, v)
}

func (s RPCTransaction) Virtual() bool {
	return capnp.Struct(s).Bit(256)
}

func (s RPCTransaction) SetVirtual(v bool) {
	capnp.Struct(s).SetBit(256, v)
}

func (s RPCTransaction) CosmosHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(15)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasCosmosHash() bool {
	return capnp.Struct(s).HasPtr(15)
}

func (s RPCTransaction) SetCosmosHash(v []byte) error {
	return capnp.Struct(s).SetData(15, v)
}

func (s RPCTransaction) TransactionIndexPresent() bool {
	return capnp.Struct(s).Bit(257)
}

func (s RPCTransaction) SetTransactionIndexPresent(v bool) {
	capnp.Struct(s).SetBit(257, v)
}

func (s RPCTransaction) BlockNumberPresent() bool {
	return capnp.Struct(s).Bit(258)
}

func (s RPCTransaction) SetBlockNumberPresent(v bool) {
	capnp.Struct(s).SetBit(258, v)
}

func (s RPCTransaction) GasPricePresent() bool {
	return capnp.Struct(s).Bit(259)
}

func (s RPCTransaction) SetGasPricePresent(v bool) {
	capnp.Struct(s).SetBit(259, v)
}

func (s RPCTransaction) GasFeeCapPresent() bool {
	return capnp.Struct(s).Bit(260)
}

func (s RPCTransaction) SetGasFeeCapPresent(v bool) {
	capnp.Struct(s).SetBit(260, v)
}

func (s RPCTransaction) GasTipCapPresent() bool {
	return capnp.Struct(s).Bit(261)
}

func (s RPCTransaction) SetGasTipCapPresent(v bool) {
	capnp.Struct(s).SetBit(261, v)
}

func (s RPCTransaction) ValuePresent() bool {
	return capnp.Struct(s).Bit(262)
}

func (s RPCTransaction) SetValuePresent(v bool) {
	capnp.Struct(s).SetBit(262, v)
}

func (s RPCTransaction) AccessesPresent() bool {
	return capnp.Struct(s).Bit(263)
}

func (s RPCTransaction) SetAccessesPresent(v bool) {
	capnp.Struct(s).SetBit(263, v)
}

func (s RPCTransaction) ChainIdPresent() bool {
	return capnp.Struct(s).Bit(264)
}

func (s RPCTransaction) SetChainIdPresent(v bool) {
	capnp.Struct(s).SetBit(264, v)
}

func (s RPCTransaction) VPresent() bool {
	return capnp.Struct(s).Bit(265)
}

func (s RPCTransaction) SetVPresent(v bool) {
	capnp.Struct(s).SetBit(265, v)
}

func (s RPCTransaction) RPresent() bool {
	return capnp.Struct(s).Bit(266)
}

func (s RPCTransaction) SetRPresent(v bool) {
	capnp.Struct(s).SetBit(266, v)
}

func (s RPCTransaction) SPresent() bool {
	return capnp.Struct(s).Bit(267)
}

func (s RPCTransaction) SetSPresent(v bool) {
	capnp.Struct(s).SetBit(267, v)
}

func (s RPCTransaction) CosmosMsgIndex() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s RPCTransaction) SetCosmosMsgIndex(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s RPCTransaction) CosmosMsgIndexPresent() bool {
	return capnp.Struct(s).Bit(268)
}

func (s RPCTransaction) SetCosmosMsgIndexPresent(v bool) {
	capnp.Struct(s).SetBit(268, v)
}

// RPCTransaction_List is a list of RPCTransaction.
type RPCTransaction_List = capnp.StructList[RPCTransaction]

// NewRPCTransaction creates a new list of RPCTransaction.
func NewRPCTransaction_List(s *capnp.Segment, sz int32) (RPCTransaction_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 16}, sz)
	return capnp.StructList[RPCTransaction](l), err
}

// RPCTransaction_Future is a wrapper for a RPCTransaction promised by a client call.
type RPCTransaction_Future struct{ *capnp.Future }

func (f RPCTransaction_Future) Struct() (RPCTransaction, error) {
	p, err := f.Future.Ptr()
	return RPCTransaction(p.Struct()), err
}

type TracePayload capnp.Struct

// TracePayload_TypeID is the unique identifier for the type TracePayload.
const TracePayload_TypeID = 0xb40b1e0176e0c004

func NewTracePayload(s *capnp.Segment) (TracePayload, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TracePayload(st), err
}

func NewRootTracePayload(s *capnp.Segment) (TracePayload, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TracePayload(st), err
}

func ReadRootTracePayload(msg *capnp.Message) (TracePayload, error) {
	root, err := msg.Root()
	return TracePayload(root.Struct()), err
}

func (s TracePayload) String() string {
	str, _ := text.Marshal(0xb40b1e0176e0c004, capnp.Struct(s))
	return str
}

func (s TracePayload) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TracePayload) DecodeFromPtr(p capnp.Ptr) TracePayload {
	return TracePayload(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TracePayload) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TracePayload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TracePayload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TracePayload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TracePayload) Raw() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s TracePayload) HasRaw() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TracePayload) SetRaw(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// TracePayload_List is a list of TracePayload.
type TracePayload_List = capnp.StructList[TracePayload]

// NewTracePayload creates a new list of TracePayload.
func NewTracePayload_List(s *capnp.Segment, sz int32) (TracePayload_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[TracePayload](l), err
}

// TracePayload_Future is a wrapper for a TracePayload promised by a client call.
type TracePayload_Future struct{ *capnp.Future }

func (f TracePayload_Future) Struct() (TracePayload, error) {
	p, err := f.Future.Ptr()
	return TracePayload(p.Struct()), err
}

type TxResult capnp.Struct

// TxResult_TypeID is the unique identifier for the type TxResult.
const TxResult_TypeID = 0xddf9c0053b56f174

func NewTxResult(s *capnp.Segment) (TxResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0})
	return TxResult(st), err
}

func NewRootTxResult(s *capnp.Segment) (TxResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0})
	return TxResult(st), err
}

func ReadRootTxResult(msg *capnp.Message) (TxResult, error) {
	root, err := msg.Root()
	return TxResult(root.Struct()), err
}

func (s TxResult) String() string {
	str, _ := text.Marshal(0xddf9c0053b56f174, capnp.Struct(s))
	return str
}

func (s TxResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TxResult) DecodeFromPtr(p capnp.Ptr) TxResult {
	return TxResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TxResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TxResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TxResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TxResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TxResult) Height() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s TxResult) SetHeight(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s TxResult) TxIndex() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s TxResult) SetTxIndex(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s TxResult) MsgIndex() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s TxResult) SetMsgIndex(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s TxResult) EthTxIndex() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s TxResult) SetEthTxIndex(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s TxResult) Failed() bool {
	return capnp.Struct(s).Bit(160)
}

func (s TxResult) SetFailed(v bool) {
	capnp.Struct(s).SetBit(160, v)
}

func (s TxResult) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s TxResult) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s TxResult) CumulativeGasUsed() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s TxResult) SetCumulativeGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

// TxResult_List is a list of TxResult.
type TxResult_List = capnp.StructList[TxResult]

// NewTxResult creates a new list of TxResult.
func NewTxResult_List(s *capnp.Segment, sz int32) (TxResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0}, sz)
	return capnp.StructList[TxResult](l), err
}

// TxResult_Future is a wrapper for a TxResult promised by a client call.
type TxResult_Future struct{ *capnp.Future }

func (f TxResult_Future) Struct() (TxResult, error) {
	p, err := f.Future.Ptr()
	return TxResult(p.Struct()), err
}

const schema_bc3f21e1d17a526c = "x\xda\xa4\x98\x7f\x88\\\xd5\xf9\xc6\xdf\xf7\x9c;3;" +
	"\xfb{ro\xe2F7\xd9]\x89\xa0\xc1|\xbf\xa6\x86" +
	"R\xb6\xda\x8d\xd9F7\xba\xb6;{W\xb1R\xc1\xbb" +
	"37\xb3\xa33s\xa7\xf7\xde\x197i\xca&bi" +
	"\xd4\x94j\x88Em\x04\x0bI\xd1\x82\x10e\x0b\x15\xd6" +
	"\xb2\x11-\xb1Dp!)\x09D\x1a\xc1\x80)\x11\xda" +
	"R\xc1\x14e\xcas\xee\xde;w\x7f4\x14\xfa\xdf\xce" +
	"\xe7}\xef9w\xce<\xef\xfb\xbcgo{6\xb9]" +
	"\xdb\xda1\xa3\x91\xc8nK$\x1bw\xbcZ\xf8\xcd\xc9" +
	"7'~F\x9947J\xe3{\x17>\x19\x18\x9a\xa3" +
	"\x04\xa7\x88\xf4\x9b\xc4\xcb\xfa\x16\x81\xbfn\x11C\xc4\x8d" +
	"\xcd\xaf\x1c\xd7\xd6\x1e\xf8\xeb\xcf\x97\xe5\xaa\x8c\x1f\x88\xdf" +
	"\xea\x96\xfa\xeb\x11\xf1\x04q\xe3\xc7[6\xfer\xf3\xb7" +
	"\x9e}\x91\xb2iN\xc4\x92\x93H\xf9P<\xa6/ " +
	"\xf9\xf6\x0f\xc5_\x04q\xe3\x03\xed>Q\x7f\xf0\x0f\xbf" +
	"Bv2\x96\xdd\x8d\xecK\x89w\xf5\xcf\x13\xc8\xbe\x9c" +
	"x\"E\xdc\xf8\xc7M\xee\xc9s\xc3\xbdG\x91\x9d\x8a" +
	"e\xa7\x90}W\xe7\xcb\xfa\xaeNd\xef\xec\xfc\xbe$" +
	"nh\xf3\x17\xeb\xbc\xb1mv\xb5o\xb8\x90yK?" +
	"\x9f\xc1_g3\xf8\x86\xa7\x9f\xec\xfcs\xe2\xfdo\x9e" +
	"\\\xber+R\xbe\xc8<\xa3\x7f\x8d\xe4\xdb\xaff\xfe" +
	"_#n\xf8\x7f\x7f\xf0\xdb\x89\xf9\xab\x1f/\xfb\x8e\x1a" +
	"\x92\x7f\xbd\xee\xb0\xfe\xfa:$\x1f_\xf7\x0b&n\xfc" +
	"\xcb~\xe1\x8d\xef\\\xf9\xe3\xe7\xab\xbd\xc6\x9d=\x87\xf5" +
	"\x9d=\xea\xed{\x86hK\xe3\xf1\xfa\xff\xe5\xacj\xa5" +
	"\xca\x83;JN\xee\xf1QG\x16\xbc1\xe6\xac&5" +
	"\"\x8d\x892\x1d\x83D\xd9\x16\xc9\xd9M\x82\x87\x0a\xae" +
	"S\xabz\xdcI<&\x99\xbb\x9b[\x11\x03\xc6\x96\xbb" +
	"+\x97\xb3=o\xa2\xabV-\xd9X\xb0%Z\xf0\x96" +
	"\x1dD\xd9M\x92\xb3\xb7\x09\xce0\x1b\x0c\xb8e\x92(" +
	"{\xab\xe4\xec\x88\xe0\x19+\x9fwm\xcf\xe3\x0e\x12\xdc" +
	"A\xdc\xf0|\xc7\xb5\x0a\xf6}\x94\xb2\xf7D\x9b#\x18" +
	"\xdf\x92\xba\x06G\x9d\x02\xb6\xda\x16n\xa5?\xc2;\x88" +
	"\xcc\x87X\xb2\x99\xe7\xe6n\xba\xc5\x83D\xe6\x0f\xc1\xa7" +
	"\xc1\x850X\x10\xe95\xdeLdV\xc1\xf7\xb1`\x96" +
	"\x06K\"}\x0fO\x12\x99\xd3\xc0O!]\x93\x06k" +
	"D\xfa\x01\xb5\xcc>\xf0\x83\xe0\x0968A\xa4\xffT" +
	"m\xbb\x1f\xfc\x10xR38I\xa4?\xcd\xe3D\xe6" +
	"A\xf0#\xe0)a\xa8\x1f\xe5y\xfe\x06\x91y\x08\xfc" +
	"E\xf0\x96y\x83[\x88\xf4\x17\xd4:\xcf\x81\x1f\x05O" +
	"\x9f48M\xa4\xbf\xa4\xf8\x11\xf0W\xc1[\x13\x06\xb7" +
	"\x12\xe9\xaf\xf0\xc3D\xe6Q\xf0\xd7\xc0\xdb4\x83\xdb\x88" +
	"\xf4\xe3\xbc\x97\xc8<\x06~\x02\xbc\xfd]\x83\xdb\x89\xf4" +
	"7\xf8-\"\xf3\x04\xf8\x1c\xaf<\xf7!\xdf\xa9\x16s" +
	"\xcb\x0f\xbc+o\xf9V\xf4\xd3LB5\xdf\xab\x95)" +
	"5i\xbb\x9c&\xc1i<8=bySa\xd2\x8c" +
	"?\xbd\xab\x92\xb7\xa7\xc3p\xf0\xd0\x88\xe5\x11G9}" +
	"\xc5x\xc6\x8ck\x97\x9d\xba\x9dg&\xc1L<S/" +
	"\xba~\xcd*\x85\x9f\x1b9\xc7+;\xde\x88E\xb2\xb9" +
	"\xcd\"\xbc\xdf\xa3\xa1\xc2\xd2\xfd\xc2\x00\x07|\xcc\xed\xb3" +
	"=\xbb\xe2G\xab\x85\x12\x12\x83\xe3c\xc3\x13\xaeU\xf1" +
	"\xac\x9c_t*\x045\x1d\x8c\xd4\xf4\xba\xc4\xcf\xf7\x9a" +
	"\x94l\xce\xca\x98\x9a\xde\x94\x90\xc7\x09\xf09\x19S\xd3" +
	"\xdb\x12j\x9a\x05\x9f\x97M5\xbd#o$2\x7f\x0f" +
	"\xfc\x9e\x8c\xa9\xe9\xa4\xbc\x97\xc8\x9c\x07?\x0d\x9e\xd0\x02" +
	"5}\xa0\xb6=\x05~\x06<\x99\x08\xd4\xb4\xa0\xf8G" +
	"\xe0\x17\xc0S\xc9@M\xe7\xd5\xb6g\xc0/\x82\xb7\xa4" +
	"\x025},\xa1\xb2s\xe0\x9f\x82\xa79P\xd3'\x8a" +
	"_\x00\xff\x0c\xbc\xb5%P\xd3%y=\x91y\x11\xfc" +
	"\x0ax\x9b\x08\xd4tY>Cd^\x01\xff\x12\xbc=" +
	"\x1d\xa8\xe9\x0b\xb5\xce\xdf\xc0\xbf\x02\xef\x90\x06w\x10\xe9" +
	"W\xd5\xfb\xfcSJ\x1e\xd7\x04g:[\x0d\xee$\xd2" +
	"\xbfV_\xf7+\xa4\xf7\x80w\xb5\x19\xdcE\xa4\xaf\xd5" +
	" \xeenM\xb2\xd9\x0b\xde\xddnp7\x91\xbe^[" +
	"Cd\x1a\xe0\xfd\xe0\x99\x0e\x833D\xfa\x06\xc5{\xc0" +
	"7\x81\xaf\xe94x\x0d\x91>\xa0x/\xf8\xcd\x9a\xe0" +
	"\x01\x9d\x0d\xd6a5j\xfd~\xf0[\x91ot\x19l" +
	"\xc0x4\x14\xcf\xcd\xe0\xdb4\xc1[\xd7\xe2\xe7]K" +
	"\xa4o\xd5\xde%2\xb7!\xb0\x1d\x81u\x82\x0d^\x87" +
	"^\xaa\xbdLdnG`\x14\x81\xeb$\x1b|\x1d\x91" +
	"\xbeK{\x92\xc8\x1cA`\x02\x81\x1e\x8d\x0d\xee!\xd2" +
	"\xb3\x1a\x8en\x02\x81G\x11X\x8f\x8e\xb1\x1e\x8dJ\x05" +
	"\x1eE\xa0\x84\xc0\xf5I6\xf8z\"\xbd\xa8=Fd" +
	"N!\xe0#pC\x8a\x0d\xbe\x81H\xff\x91\xda\xa3\x8a" +
	"\xc0>\x04z[\xd8\xe0^4+\x0d\xc5>\x8d\xc0S" +
	"\x08l\xc0\xef\xbc\x01\xddJ\xc3\x81\xefG\xe0\x10\x02\x1b" +
	"[\xd9\xe0\x8dhK*p\x10\x81#\x08\xf4\xb5\xb1\xc1" +
	"}\xe8K*\xf0\x1c\x02GqT\xfd\x09\x83\xfb\xd1\x7f" +
	"\xd4\x16/\x82\x1f\xc3\x03\x03\xedl\xf0\x00\xacHCC" +
	"9\x86\xc0\x09M\xacZ\xe8\xcb:\xc6\"\xed\xda\xed:" +
	"\xe5\xf0C\xaa`yQ\xed\x16,o\xcc-\xe6l\"" +
	"\x8a\x96(X\xde\xdd\xb6=l\x11W\xe3l\xa2X]" +
	"\xc2\xba\xa6bM\xa8\xafX\xa9\xd6\xfc\xe8S\xc5\xa9\xe4" +
	"\xecp\x13\xe9;\xd1:\xfeb\xf9s\xd1\xa9\xa8nA" +
	"\x14\xa6\xf5\xd5\xadR\xcd\x8eV\xf7\xf7T\xa3\x15\x1a\x96" +
	"\xb2;\xdb#\xa2\xa6;FSL\xe0\x8e3\xb9)\xab" +
	"X\xd9\x95\x0fW\xe0z\xf4Wt\x10\x1cu\xdf\xff\xae" +
	"\xe7\x85\xaf+\xc2\xd7\x1dsUo\xa3\xe8\xb1\xf0\xbcy" +
	"\xd2vUP\xc6:_x\xba\xbc\xe2\xb1\xf0\x8c\xb9\x1a" +
	"\x86\x96\xc4\xd4Y\xaf\x16Sg4\xe6\xda\xd4\xb5\xa4\xc5" +
	"\x86\xe7\xb3r\xa3\xc5C\x19\xa3!wiW\xaeG\x8b" +
	"7\x93\xddU\x98\xb7\x0a\xfb\x9f\xad`q\x1e\xba\xdf\x96" +
	"\xbe\x05\x17\xb8#r\x81\x17x0n\xca\xa1\x09\xbc\xc4" +
	"\x9b\x97x\xb2\xe0\xc0\x04\x96{\xb2\x14\x81\x0b\x1c\xe7\xf1" +
	"%\x9e\x1c\xba\xc0\x1bj\x16x\x0d|6>S\xbc\xc9" +
	"\xe3q\xaf\xce$E\xe0\x02o\xab}g\xc1\xe7\xc1S" +
	"2p\x81w\x18\xb5;\x07~J\xcd\x14Z\xe0\x02\xef" +
	"\xab\xd9a\x1e\xfc4x\xba5p\x81\x0f\xd4{\x9e\x02" +
	"?\xa3f\x8a\xb6\xc0\x05\x16T\xfei\xf0s\xf1\x99\xe2" +
	"\xacz\xcf\x8f\xc0/\x80\xb7'\x02\x178\xcf\xe8d\x17" +
	"\xc0?\x03\xefH\x06.pI\xads\x11\xfc\x0a\x0b\xde" +
	"\xda\xb9\x9f\x03\x1f\xb8\xcch\xafW\x10\xf8\x92\x05\x0fM" +
	"\xd9\xc5\xc2\x94\xcf\x09\x12\x9c\x08k\xb8\x9d\x04\xb7\x137" +
	"\xaa\x96kW\xfc\xc5\x12\x08\xa1\xe7[\xbe=\xee8\xc4" +
	"~\xc8\xfa\xca\xc5\x8a\xedF\x19~\xb1l{\xbeU&" +
	"\xaeF\xebz\xc5\xbdv\xbc\xc9\x8c\x16\xcbE%\xa1p" +
	"\x04)X\xde\x03\x9e\x9d\x8frl\x7fjbz\xd8\xa9" +
	"\x11\xeaG#\xc1\x9a\x9al\x86\x9dZ\xf3s\xdfd\xc9" +
	"q\xca\xcd}c\xbd\xc4\x1bw\x1c\x9f(\x8c\xcdLZ" +
	"\x9e}\xb7mG\xb9\x8b\xd5^\x14{\xed\xfc\xb0\x12\xe9" +
	"\xce\xba]\xf1=ZE\x9a\x13\xae\x95\xb3\xc7\xac\xbe=" +
	"%\xc7\xca/\x9b\xd6o\\\x9c\xd6\x0d\xc1)\xd7z\"" +
	"j\x14\xcd\xa7\xc7\xed\x9c]\xac\xfa\xa4\xa6\x9b\xd1H\xd7" +
	"\x091H4.$\x9b\xed\"6\xdc\xa4\xc5a\"\xb3" +
	"\x1d\xbcG\xc4\x86\x9b\xb5B\xd94x\xafh\x0e7\xeb" +
	"\xb1\x8ai\x00\xf7#]\xe3@\xd6\x1bTz\x0f\xf8&" +
	"\xf0\x84\x08d=  \xeb~\xf0[\xc1\x932\x90\xf5" +
	"-\x02\xb2\xde\x04\xbe\x1d<\xa5\x05\xb2\xbeS\xc0\xf6\xee" +
	"\x00\x1f\x01oI\x04\xb2\xde\xa9\xf8w\xc1\xc7\xc0\xd3\xc9" +
	"@\xd6\xf7\xab\xf5G\xc1\x1f\x02o\x95\x81\xac\x1f\x10\x98" +
	"\xd9&\xc0\x1f\x151Y?\"\x94\x11\x83\x97\xc0\xdbS" +
	"\x81\xac\x8b\xea\x18J\xe0\xd3\xe0\x1d-\x81\xack\xea=" +
	"\xab\xe0\xfb\xc0;\xd3\x81\xaa\xf7\x08\x0cO>\xf8~\xf0" +
	"\xaeD0\xdd\xfcD\xe5O\x83?%\x04o\xed\xde\xcf" +
	"\xc1xs@\xb8pg\x04\x0e!\x909\xc0\xc1|\xf3" +
	"\xb4\x80\xd9\x1eD\xe0\x08\x02k\x9e\xe4`\xc0y^\xfc" +
	"\x09.\x8c\xc01!x\x08uPk\x1ag\xaeV\xae" +
	"\x95,\xbf\xc8u\xfb\x1e%e\xce\xff'm\x0f\xb9\xb6" +
	"\xe59\x95H\x9b\xf5\xf2N\xd7u\x9a\xf5Sr\x0a\xde" +
	"\x8e\x12*,\xf2\xe8.\xb0\xa6\xd3Ew\xf0\xc5{`" +
	"\\\xf9\xb8\x0aPlH\xaf\xf8.\"w\x05\x97\x0dZ" +
	":\x18\\sX\x08\xbf\xda5<\xbaa\xef\xdem\xe7" +
	"\xfcb\x9d\xed{\x02oc{\xd5!#\xe6\xf9K\x9d" +
	"<8\x8b1\x97\x969\xc3\xe2\xa1\xac\xf4\xa9pG\x11" +
	"\xeeh\xaft\xc5X\xedN\x8f\xdb^\xad\xc4>\xaa\xaf" +
	"7\xaa\xdb\xdf\xe1\x96}Brv\x0e\xb5'\x82K\xf1" +
	"\xdb\xb8)\xcfJ\xce\xce\xa3\xf0\xa4*\xbc\xcc;\xf7\x12" +
	"e\xe7$gO\xc1M4Uv\x99\xf7\x1f&\xca\xbe" +
	"'9\xfb\x11j\xeeUUs\x99\x0f\xb1\xe6)\xc9\xd9" +
	"3(8\xa9\x0a.\xb3\x805OK\xce\x9ek^L" +
	"3g\x0f\x13e\xcfI\xce~\xba\xa2\x01G\x97\xb7\x16" +
	"\x12\xdcB\xdc({\x85\xc53\xa7\x88\xa9\xde\xb8\xab\x92" +
	"'iO\x87\xbdph\xb7U,\xc5\xaep\xcb\xfb\xe9" +
	"5\xf4\x19;\xaeQ\xa7p\x8f\xeb\xd4\xb8\xba\xac\xcdm" +
	"n\xfeS\xe2\xdaR\xfc\xf7\x00\xd2\xd9\x94\xf2"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bc3f21e1d17a526c,
		Nodes: []uint64{
			0x8754b1c1a667a03c,
			0x8dea811504a59d2a,
			0x988b382a961e2d7b,
			0x9bbe5676024b04c9,
			0x9c1c43d8c17225f2,
			0xb40b1e0176e0c004,
			0xc136c505d60e82cc,
			0xddf9c0053b56f174,
			0xedc6ec3ead9565fa,
		},
		Compressed: true,
	})
}
