// Code generated by capnpc-go. DO NOT EDIT.

package kvcapnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type BlockMeta capnp.Struct

// BlockMeta_TypeID is the unique identifier for the type BlockMeta.
const BlockMeta_TypeID = 0x9c1c43d8c17225f2

func NewBlockMeta(s *capnp.Segment) (BlockMeta, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7})
	return BlockMeta(st), err
}

func NewRootBlockMeta(s *capnp.Segment) (BlockMeta, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7})
	return BlockMeta(st), err
}

func ReadRootBlockMeta(msg *capnp.Message) (BlockMeta, error) {
	root, err := msg.Root()
	return BlockMeta(root.Struct()), err
}

func (s BlockMeta) String() string {
	str, _ := text.Marshal(0x9c1c43d8c17225f2, capnp.Struct(s))
	return str
}

func (s BlockMeta) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BlockMeta) DecodeFromPtr(p capnp.Ptr) BlockMeta {
	return BlockMeta(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BlockMeta) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BlockMeta) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BlockMeta) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BlockMeta) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BlockMeta) Height() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s BlockMeta) SetHeight(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s BlockMeta) Hash() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BlockMeta) HasHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BlockMeta) HashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BlockMeta) SetHash(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BlockMeta) ParentHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BlockMeta) HasParentHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BlockMeta) ParentHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BlockMeta) SetParentHash(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s BlockMeta) StateRoot() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s BlockMeta) HasStateRoot() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s BlockMeta) StateRootBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s BlockMeta) SetStateRoot(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s BlockMeta) Miner() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s BlockMeta) HasMiner() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s BlockMeta) MinerBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s BlockMeta) SetMiner(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s BlockMeta) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s BlockMeta) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s BlockMeta) Size() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s BlockMeta) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s BlockMeta) GasLimit() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s BlockMeta) SetGasLimit(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s BlockMeta) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s BlockMeta) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s BlockMeta) EthTxCount() int32 {
	return int32(capnp.Struct(s).Uint32(40))
}

func (s BlockMeta) SetEthTxCount(v int32) {
	capnp.Struct(s).SetUint32(40, uint32(v))
}

func (s BlockMeta) TxCount() int32 {
	return int32(capnp.Struct(s).Uint32(44))
}

func (s BlockMeta) SetTxCount(v int32) {
	capnp.Struct(s).SetUint32(44, uint32(v))
}

func (s BlockMeta) Bloom() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s BlockMeta) HasBloom() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s BlockMeta) BloomBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s BlockMeta) SetBloom(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s BlockMeta) TransactionsRoot() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s BlockMeta) HasTransactionsRoot() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s BlockMeta) TransactionsRootBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s BlockMeta) SetTransactionsRoot(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s BlockMeta) BaseFee() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s BlockMeta) HasBaseFee() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s BlockMeta) BaseFeeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s BlockMeta) SetBaseFee(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s BlockMeta) VirtualizedCosmosEvents() bool {
	return capnp.Struct(s).Bit(384)
}

func (s BlockMeta) SetVirtualizedCosmosEvents(v bool) {
	capnp.Struct(s).SetBit(384, v)
}

// BlockMeta_List is a list of BlockMeta.
type BlockMeta_List = capnp.StructList[BlockMeta]

// NewBlockMeta creates a new list of BlockMeta.
func NewBlockMeta_List(s *capnp.Segment, sz int32) (BlockMeta_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 7}, sz)
	return capnp.StructList[BlockMeta](l), err
}

// BlockMeta_Future is a wrapper for a BlockMeta promised by a client call.
type BlockMeta_Future struct{ *capnp.Future }

func (f BlockMeta_Future) Struct() (BlockMeta, error) {
	p, err := f.Future.Ptr()
	return BlockMeta(p.Struct()), err
}

type Log capnp.Struct

// Log_TypeID is the unique identifier for the type Log.
const Log_TypeID = 0x988b382a961e2d7b

func NewLog(s *capnp.Segment) (Log, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return Log(st), err
}

func NewRootLog(s *capnp.Segment) (Log, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return Log(st), err
}

func ReadRootLog(msg *capnp.Message) (Log, error) {
	root, err := msg.Root()
	return Log(root.Struct()), err
}

func (s Log) String() string {
	str, _ := text.Marshal(0x988b382a961e2d7b, capnp.Struct(s))
	return str
}

func (s Log) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Log) DecodeFromPtr(p capnp.Ptr) Log {
	return Log(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Log) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Log) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Log) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Log) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Log) Address() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Log) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Log) SetAddress(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Log) Topics() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.DataList(p.List()), err
}

func (s Log) HasTopics() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Log) SetTopics(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewTopics sets the topics field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s Log) NewTopics(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Log) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Log) HasData() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Log) SetData(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Log) BlockNumber() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Log) SetBlockNumber(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Log) TxHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Log) HasTxHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Log) SetTxHash(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Log) TxIndex() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Log) SetTxIndex(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Log) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Log) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Log) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Log) Index() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Log) SetIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Log) Removed() bool {
	return capnp.Struct(s).Bit(192)
}

func (s Log) SetRemoved(v bool) {
	capnp.Struct(s).SetBit(192, v)
}

func (s Log) Virtual() bool {
	return capnp.Struct(s).Bit(193)
}

func (s Log) SetVirtual(v bool) {
	capnp.Struct(s).SetBit(193, v)
}

func (s Log) CosmosHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s Log) HasCosmosHash() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Log) SetCosmosHash(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

// Log_List is a list of Log.
type Log_List = capnp.StructList[Log]

// NewLog creates a new list of Log.
func NewLog_List(s *capnp.Segment, sz int32) (Log_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6}, sz)
	return capnp.StructList[Log](l), err
}

// Log_Future is a wrapper for a Log promised by a client call.
type Log_Future struct{ *capnp.Future }

func (f Log_Future) Struct() (Log, error) {
	p, err := f.Future.Ptr()
	return Log(p.Struct()), err
}

type LogGroup capnp.Struct

// LogGroup_TypeID is the unique identifier for the type LogGroup.
const LogGroup_TypeID = 0xedc6ec3ead9565fa

func NewLogGroup(s *capnp.Segment) (LogGroup, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LogGroup(st), err
}

func NewRootLogGroup(s *capnp.Segment) (LogGroup, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LogGroup(st), err
}

func ReadRootLogGroup(msg *capnp.Message) (LogGroup, error) {
	root, err := msg.Root()
	return LogGroup(root.Struct()), err
}

func (s LogGroup) String() string {
	str, _ := text.Marshal(0xedc6ec3ead9565fa, capnp.Struct(s))
	return str
}

func (s LogGroup) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LogGroup) DecodeFromPtr(p capnp.Ptr) LogGroup {
	return LogGroup(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LogGroup) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LogGroup) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LogGroup) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LogGroup) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LogGroup) Logs() (Log_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Log_List(p.List()), err
}

func (s LogGroup) HasLogs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LogGroup) SetLogs(v Log_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewLogs sets the logs field to a newly
// allocated Log_List, preferring placement in s's segment.
func (s LogGroup) NewLogs(n int32) (Log_List, error) {
	l, err := NewLog_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Log_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// LogGroup_List is a list of LogGroup.
type LogGroup_List = capnp.StructList[LogGroup]

// NewLogGroup creates a new list of LogGroup.
func NewLogGroup_List(s *capnp.Segment, sz int32) (LogGroup_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[LogGroup](l), err
}

// LogGroup_Future is a wrapper for a LogGroup promised by a client call.
type LogGroup_Future struct{ *capnp.Future }

func (f LogGroup_Future) Struct() (LogGroup, error) {
	p, err := f.Future.Ptr()
	return LogGroup(p.Struct()), err
}

type BlockLogs capnp.Struct

// BlockLogs_TypeID is the unique identifier for the type BlockLogs.
const BlockLogs_TypeID = 0x8754b1c1a667a03c

func NewBlockLogs(s *capnp.Segment) (BlockLogs, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BlockLogs(st), err
}

func NewRootBlockLogs(s *capnp.Segment) (BlockLogs, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return BlockLogs(st), err
}

func ReadRootBlockLogs(msg *capnp.Message) (BlockLogs, error) {
	root, err := msg.Root()
	return BlockLogs(root.Struct()), err
}

func (s BlockLogs) String() string {
	str, _ := text.Marshal(0x8754b1c1a667a03c, capnp.Struct(s))
	return str
}

func (s BlockLogs) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BlockLogs) DecodeFromPtr(p capnp.Ptr) BlockLogs {
	return BlockLogs(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BlockLogs) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BlockLogs) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BlockLogs) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BlockLogs) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BlockLogs) Groups() (LogGroup_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return LogGroup_List(p.List()), err
}

func (s BlockLogs) HasGroups() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BlockLogs) SetGroups(v LogGroup_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewGroups sets the groups field to a newly
// allocated LogGroup_List, preferring placement in s's segment.
func (s BlockLogs) NewGroups(n int32) (LogGroup_List, error) {
	l, err := NewLogGroup_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return LogGroup_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// BlockLogs_List is a list of BlockLogs.
type BlockLogs_List = capnp.StructList[BlockLogs]

// NewBlockLogs creates a new list of BlockLogs.
func NewBlockLogs_List(s *capnp.Segment, sz int32) (BlockLogs_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[BlockLogs](l), err
}

// BlockLogs_Future is a wrapper for a BlockLogs promised by a client call.
type BlockLogs_Future struct{ *capnp.Future }

func (f BlockLogs_Future) Struct() (BlockLogs, error) {
	p, err := f.Future.Ptr()
	return BlockLogs(p.Struct()), err
}

type Receipt capnp.Struct

// Receipt_TypeID is the unique identifier for the type Receipt.
const Receipt_TypeID = 0xc136c505d60e82cc

func NewReceipt(s *capnp.Segment) (Receipt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10})
	return Receipt(st), err
}

func NewRootReceipt(s *capnp.Segment) (Receipt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10})
	return Receipt(st), err
}

func ReadRootReceipt(msg *capnp.Message) (Receipt, error) {
	root, err := msg.Root()
	return Receipt(root.Struct()), err
}

func (s Receipt) String() string {
	str, _ := text.Marshal(0xc136c505d60e82cc, capnp.Struct(s))
	return str
}

func (s Receipt) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Receipt) DecodeFromPtr(p capnp.Ptr) Receipt {
	return Receipt(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Receipt) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Receipt) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Receipt) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Receipt) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Receipt) Status() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Receipt) SetStatus(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Receipt) CumulativeGasUsed() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Receipt) SetCumulativeGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Receipt) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Receipt) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Receipt) Reason() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Receipt) HasReason() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Receipt) ReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Receipt) SetReason(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Receipt) VmError() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Receipt) HasVmError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Receipt) VmErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Receipt) SetVmError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Receipt) LogsBloom() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Receipt) HasLogsBloom() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Receipt) SetLogsBloom(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Receipt) Logs() (Log_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Log_List(p.List()), err
}

func (s Receipt) HasLogs() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Receipt) SetLogs(v Log_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewLogs sets the logs field to a newly
// allocated Log_List, preferring placement in s's segment.
func (s Receipt) NewLogs(n int32) (Log_List, error) {
	l, err := NewLog_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Log_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Receipt) TransactionHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Receipt) HasTransactionHash() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Receipt) SetTransactionHash(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Receipt) ContractAddress() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s Receipt) HasContractAddress() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Receipt) SetContractAddress(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

func (s Receipt) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return []byte(p.Data()), err
}

func (s Receipt) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Receipt) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(6, v)
}

func (s Receipt) BlockNumber() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s Receipt) SetBlockNumber(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s Receipt) TransactionIndex() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Receipt) SetTransactionIndex(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Receipt) EffectiveGasPrice() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s Receipt) HasEffectiveGasPrice() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Receipt) SetEffectiveGasPrice(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

func (s Receipt) From() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return []byte(p.Data()), err
}

func (s Receipt) HasFrom() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Receipt) SetFrom(v []byte) error {
	return capnp.Struct(s).SetData(8, v)
}

func (s Receipt) To() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return []byte(p.Data()), err
}

func (s Receipt) HasTo() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Receipt) SetTo(v []byte) error {
	return capnp.Struct(s).SetData(9, v)
}

func (s Receipt) Type() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s Receipt) SetType(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s Receipt) ReasonPresent() bool {
	return capnp.Struct(s).Bit(384)
}

func (s Receipt) SetReasonPresent(v bool) {
	capnp.Struct(s).SetBit(384, v)
}

func (s Receipt) VmErrorPresent() bool {
	return capnp.Struct(s).Bit(385)
}

func (s Receipt) SetVmErrorPresent(v bool) {
	capnp.Struct(s).SetBit(385, v)
}

func (s Receipt) EffectiveGasPricePresent() bool {
	return capnp.Struct(s).Bit(386)
}

func (s Receipt) SetEffectiveGasPricePresent(v bool) {
	capnp.Struct(s).SetBit(386, v)
}

// Receipt_List is a list of Receipt.
type Receipt_List = capnp.StructList[Receipt]

// NewReceipt creates a new list of Receipt.
func NewReceipt_List(s *capnp.Segment, sz int32) (Receipt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 10}, sz)
	return capnp.StructList[Receipt](l), err
}

// Receipt_Future is a wrapper for a Receipt promised by a client call.
type Receipt_Future struct{ *capnp.Future }

func (f Receipt_Future) Struct() (Receipt, error) {
	p, err := f.Future.Ptr()
	return Receipt(p.Struct()), err
}

type AccessTuple capnp.Struct

// AccessTuple_TypeID is the unique identifier for the type AccessTuple.
const AccessTuple_TypeID = 0x8dea811504a59d2a

func NewAccessTuple(s *capnp.Segment) (AccessTuple, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return AccessTuple(st), err
}

func NewRootAccessTuple(s *capnp.Segment) (AccessTuple, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return AccessTuple(st), err
}

func ReadRootAccessTuple(msg *capnp.Message) (AccessTuple, error) {
	root, err := msg.Root()
	return AccessTuple(root.Struct()), err
}

func (s AccessTuple) String() string {
	str, _ := text.Marshal(0x8dea811504a59d2a, capnp.Struct(s))
	return str
}

func (s AccessTuple) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AccessTuple) DecodeFromPtr(p capnp.Ptr) AccessTuple {
	return AccessTuple(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AccessTuple) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AccessTuple) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AccessTuple) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AccessTuple) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AccessTuple) Address() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s AccessTuple) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AccessTuple) SetAddress(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s AccessTuple) StorageKeys() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.DataList(p.List()), err
}

func (s AccessTuple) HasStorageKeys() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AccessTuple) SetStorageKeys(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewStorageKeys sets the storageKeys field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s AccessTuple) NewStorageKeys(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// AccessTuple_List is a list of AccessTuple.
type AccessTuple_List = capnp.StructList[AccessTuple]

// NewAccessTuple creates a new list of AccessTuple.
func NewAccessTuple_List(s *capnp.Segment, sz int32) (AccessTuple_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[AccessTuple](l), err
}

// AccessTuple_Future is a wrapper for a AccessTuple promised by a client call.
type AccessTuple_Future struct{ *capnp.Future }

func (f AccessTuple_Future) Struct() (AccessTuple, error) {
	p, err := f.Future.Ptr()
	return AccessTuple(p.Struct()), err
}

type RPCTransaction capnp.Struct

// RPCTransaction_TypeID is the unique identifier for the type RPCTransaction.
const RPCTransaction_TypeID = 0x9bbe5676024b04c9

func NewRPCTransaction(s *capnp.Segment) (RPCTransaction, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 16})
	return RPCTransaction(st), err
}

func NewRootRPCTransaction(s *capnp.Segment) (RPCTransaction, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 16})
	return RPCTransaction(st), err
}

func ReadRootRPCTransaction(msg *capnp.Message) (RPCTransaction, error) {
	root, err := msg.Root()
	return RPCTransaction(root.Struct()), err
}

func (s RPCTransaction) String() string {
	str, _ := text.Marshal(0x9bbe5676024b04c9, capnp.Struct(s))
	return str
}

func (s RPCTransaction) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCTransaction) DecodeFromPtr(p capnp.Ptr) RPCTransaction {
	return RPCTransaction(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCTransaction) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCTransaction) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCTransaction) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCTransaction) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCTransaction) BlockHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasBlockHash() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCTransaction) SetBlockHash(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s RPCTransaction) BlockNumber() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasBlockNumber() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCTransaction) SetBlockNumber(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s RPCTransaction) From() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasFrom() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RPCTransaction) SetFrom(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s RPCTransaction) Gas() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s RPCTransaction) SetGas(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s RPCTransaction) GasPrice() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasPrice() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s RPCTransaction) SetGasPrice(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s RPCTransaction) GasFeeCap() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasFeeCap() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s RPCTransaction) SetGasFeeCap(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s RPCTransaction) GasTipCap() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasGasTipCap() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s RPCTransaction) SetGasTipCap(v []byte) error {
	return capnp.Struct(s).SetData(5, v)
}

func (s RPCTransaction) Hash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasHash() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s RPCTransaction) SetHash(v []byte) error {
	return capnp.Struct(s).SetData(6, v)
}

func (s RPCTransaction) Input() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasInput() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s RPCTransaction) SetInput(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

func (s RPCTransaction) Nonce() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s RPCTransaction) SetNonce(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s RPCTransaction) To() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasTo() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s RPCTransaction) SetTo(v []byte) error {
	return capnp.Struct(s).SetData(8, v)
}

func (s RPCTransaction) TransactionIndex() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s RPCTransaction) SetTransactionIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s RPCTransaction) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasValue() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s RPCTransaction) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(9, v)
}

func (s RPCTransaction) Type() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s RPCTransaction) SetType(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s RPCTransaction) Accesses() (AccessTuple_List, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return AccessTuple_List(p.List()), err
}

func (s RPCTransaction) HasAccesses() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s RPCTransaction) SetAccesses(v AccessTuple_List) error {
	return capnp.Struct(s).SetPtr(10, v.ToPtr())
}

// NewAccesses sets the accesses field to a newly
// allocated AccessTuple_List, preferring placement in s's segment.
func (s RPCTransaction) NewAccesses(n int32) (AccessTuple_List, error) {
	l, err := NewAccessTuple_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return AccessTuple_List{}, err
	}
	err = capnp.Struct(s).SetPtr(10, l.ToPtr())
	return l, err
}
func (s RPCTransaction) ChainId() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasChainId() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s RPCTransaction) SetChainId(v []byte) error {
	return capnp.Struct(s).SetData(11, v)
}

func (s RPCTransaction) V() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasV() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s RPCTransaction) SetV(v []byte) error {
	return capnp.Struct(s).SetData(12, v)
}

func (s RPCTransaction) R() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasR() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s RPCTransaction) SetR(v []byte) error {
	return capnp.Struct(s).SetData(13, v)
}

func (s RPCTransaction) S() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasS() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s RPCTransaction) SetS(v []byte) error {
	return capnp.Struct(s).SetData(14, v)
}

func (s RPCTransaction) Virtual() bool {
	return capnp.Struct(s).Bit(256)
}

func (s RPCTransaction) SetVirtual(v bool) {
	capnp.Struct(s).SetBit(256, v)
}

func (s RPCTransaction) CosmosHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(15)
	return []byte(p.Data()), err
}

func (s RPCTransaction) HasCosmosHash() bool {
	return capnp.Struct(s).HasPtr(15)
}

func (s RPCTransaction) SetCosmosHash(v []byte) error {
	return capnp.Struct(s).SetData(15, v)
}

func (s RPCTransaction) TransactionIndexPresent() bool {
	return capnp.Struct(s).Bit(257)
}

func (s RPCTransaction) SetTransactionIndexPresent(v bool) {
	capnp.Struct(s).SetBit(257, v)
}

func (s RPCTransaction) BlockNumberPresent() bool {
	return capnp.Struct(s).Bit(258)
}

func (s RPCTransaction) SetBlockNumberPresent(v bool) {
	capnp.Struct(s).SetBit(258, v)
}

func (s RPCTransaction) GasPricePresent() bool {
	return capnp.Struct(s).Bit(259)
}

func (s RPCTransaction) SetGasPricePresent(v bool) {
	capnp.Struct(s).SetBit(259, v)
}

func (s RPCTransaction) GasFeeCapPresent() bool {
	return capnp.Struct(s).Bit(260)
}

func (s RPCTransaction) SetGasFeeCapPresent(v bool) {
	capnp.Struct(s).SetBit(260, v)
}

func (s RPCTransaction) GasTipCapPresent() bool {
	return capnp.Struct(s).Bit(261)
}

func (s RPCTransaction) SetGasTipCapPresent(v bool) {
	capnp.Struct(s).SetBit(261, v)
}

func (s RPCTransaction) ValuePresent() bool {
	return capnp.Struct(s).Bit(262)
}

func (s RPCTransaction) SetValuePresent(v bool) {
	capnp.Struct(s).SetBit(262, v)
}

func (s RPCTransaction) AccessesPresent() bool {
	return capnp.Struct(s).Bit(263)
}

func (s RPCTransaction) SetAccessesPresent(v bool) {
	capnp.Struct(s).SetBit(263, v)
}

func (s RPCTransaction) ChainIdPresent() bool {
	return capnp.Struct(s).Bit(264)
}

func (s RPCTransaction) SetChainIdPresent(v bool) {
	capnp.Struct(s).SetBit(264, v)
}

func (s RPCTransaction) VPresent() bool {
	return capnp.Struct(s).Bit(265)
}

func (s RPCTransaction) SetVPresent(v bool) {
	capnp.Struct(s).SetBit(265, v)
}

func (s RPCTransaction) RPresent() bool {
	return capnp.Struct(s).Bit(266)
}

func (s RPCTransaction) SetRPresent(v bool) {
	capnp.Struct(s).SetBit(266, v)
}

func (s RPCTransaction) SPresent() bool {
	return capnp.Struct(s).Bit(267)
}

func (s RPCTransaction) SetSPresent(v bool) {
	capnp.Struct(s).SetBit(267, v)
}

// RPCTransaction_List is a list of RPCTransaction.
type RPCTransaction_List = capnp.StructList[RPCTransaction]

// NewRPCTransaction creates a new list of RPCTransaction.
func NewRPCTransaction_List(s *capnp.Segment, sz int32) (RPCTransaction_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 16}, sz)
	return capnp.StructList[RPCTransaction](l), err
}

// RPCTransaction_Future is a wrapper for a RPCTransaction promised by a client call.
type RPCTransaction_Future struct{ *capnp.Future }

func (f RPCTransaction_Future) Struct() (RPCTransaction, error) {
	p, err := f.Future.Ptr()
	return RPCTransaction(p.Struct()), err
}

type TracePayload capnp.Struct

// TracePayload_TypeID is the unique identifier for the type TracePayload.
const TracePayload_TypeID = 0xb40b1e0176e0c004

func NewTracePayload(s *capnp.Segment) (TracePayload, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TracePayload(st), err
}

func NewRootTracePayload(s *capnp.Segment) (TracePayload, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TracePayload(st), err
}

func ReadRootTracePayload(msg *capnp.Message) (TracePayload, error) {
	root, err := msg.Root()
	return TracePayload(root.Struct()), err
}

func (s TracePayload) String() string {
	str, _ := text.Marshal(0xb40b1e0176e0c004, capnp.Struct(s))
	return str
}

func (s TracePayload) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TracePayload) DecodeFromPtr(p capnp.Ptr) TracePayload {
	return TracePayload(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TracePayload) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TracePayload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TracePayload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TracePayload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TracePayload) Raw() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s TracePayload) HasRaw() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TracePayload) SetRaw(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// TracePayload_List is a list of TracePayload.
type TracePayload_List = capnp.StructList[TracePayload]

// NewTracePayload creates a new list of TracePayload.
func NewTracePayload_List(s *capnp.Segment, sz int32) (TracePayload_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[TracePayload](l), err
}

// TracePayload_Future is a wrapper for a TracePayload promised by a client call.
type TracePayload_Future struct{ *capnp.Future }

func (f TracePayload_Future) Struct() (TracePayload, error) {
	p, err := f.Future.Ptr()
	return TracePayload(p.Struct()), err
}

type TxResult capnp.Struct

// TxResult_TypeID is the unique identifier for the type TxResult.
const TxResult_TypeID = 0xddf9c0053b56f174

func NewTxResult(s *capnp.Segment) (TxResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0})
	return TxResult(st), err
}

func NewRootTxResult(s *capnp.Segment) (TxResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0})
	return TxResult(st), err
}

func ReadRootTxResult(msg *capnp.Message) (TxResult, error) {
	root, err := msg.Root()
	return TxResult(root.Struct()), err
}

func (s TxResult) String() string {
	str, _ := text.Marshal(0xddf9c0053b56f174, capnp.Struct(s))
	return str
}

func (s TxResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TxResult) DecodeFromPtr(p capnp.Ptr) TxResult {
	return TxResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TxResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TxResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TxResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TxResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TxResult) Height() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s TxResult) SetHeight(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s TxResult) TxIndex() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s TxResult) SetTxIndex(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s TxResult) MsgIndex() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s TxResult) SetMsgIndex(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s TxResult) EthTxIndex() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s TxResult) SetEthTxIndex(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s TxResult) Failed() bool {
	return capnp.Struct(s).Bit(160)
}

func (s TxResult) SetFailed(v bool) {
	capnp.Struct(s).SetBit(160, v)
}

func (s TxResult) GasUsed() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s TxResult) SetGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s TxResult) CumulativeGasUsed() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s TxResult) SetCumulativeGasUsed(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

// TxResult_List is a list of TxResult.
type TxResult_List = capnp.StructList[TxResult]

// NewTxResult creates a new list of TxResult.
func NewTxResult_List(s *capnp.Segment, sz int32) (TxResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 0}, sz)
	return capnp.StructList[TxResult](l), err
}

// TxResult_Future is a wrapper for a TxResult promised by a client call.
type TxResult_Future struct{ *capnp.Future }

func (f TxResult_Future) Struct() (TxResult, error) {
	p, err := f.Future.Ptr()
	return TxResult(p.Struct()), err
}

const schema_bc3f21e1d17a526c = "x\xda\x8c\x97\x7f\x88\x14\xe7\xfd\xc7?\x9f\xe7\x99\xbd\xdd" +
	"\xfb\xb1w\xb7\xce\\\xfc\x91\xd3\xd3\xa0\x10E\xbf_\xaf" +
	"I\x8b\xbdjO=M\xce\xe4lwo/\xc1\x04\x03" +
	"\xce\xed\x8e{\x9b\xec\xeelgf/\xa7\xb5\x9cJJ" +
	"M\x9a\xd2DL\x89V\xc1\x80\x16[*h\xb9B\x03" +
	"g9\x83\x16-\x0a\x11\x92b\xc1\x80\x01\x03\xa6\x18\x88" +
	"\xa5\x85\xa6\x04\xb6\xbc\x9f\xb9\x99]\xef\xae\xd2\xffv_" +
	"\xef\xcf~\x9e\xd9\xe7\xf3s\xd6nk\xd8\xa8u\xc7\xc7" +
	"5\x12\xa9'#\x0d\xd5\xf5's\xbf\xbax~\xe8'" +
	"\x94h\xe4jap\xef\x8dO\x97\xf5NR\x84\xa3D" +
	"\xfa\x0aqL_#\xf0i\xa5\xe8%\xae\xae:qZ" +
	"\xeb8\xf0\xb7\x9f\xcd\xb0U\x16/\x88\xdf\xe8\xa6\xfa\xf4" +
	"\x92x\x95\xb8\xfa\xc35K~\xb1j\xddO\xdf\xa5T" +
	"#ku\xc6\x0d0\xb9.^\xd6o\xc0\xf8\x89\xeb\xc2" +
	"\x16\xc4\xd5\xab\xda\xb3b\xf4\xf9?\xfe\x12\xd6\x91:\xeb" +
	"vX\x9b\x91\x0f\xf4|\x04\xd6V$\x1a%\xae\xfe}" +
	"\x85s\xf1f_\xe7qXG\xeb\xac\xa3\xb0\xfev\xfc" +
	"\x98\xbe)\x0e\xeb\x0d\xf1\xefK\xe2\xaa6u{\x94\x97" +
	"4O\xcc\xf5\x0f\xaf\xb6\xffN\xbf\xa1\x0e\xb9\xde\x8e\x7f" +
	"x\xed`\xeb_\"\x97\xbfuq\xa6\xe7&\x98|\xd1" +
	"\xfe\x86\xfeO\x18?q\xbf\xfd\xff5\xe2\xaaw\xff\xf9" +
	"\xefD\xa6\xbe\xfad\xc6Sk0>\xdaqX\x7f\xaf" +
	"\x03\xc6':~\xce\xc4\xd5\x7f[\xef\x9c\xfd\xee\xbd?" +
	"}1\xd7c|s\xfea}\xc3|\xf5\xf4\xf3{i" +
	"M\xf5\x95\xd1\xff\xcb\x98\xe5R\x99{6\x17\xec\xcc+" +
	"\x03\xb6\xcc\xb9I\xe6\x94&5\"\x8d\x89\x12\xf1\x1e\xa2" +
	"TLrj\xb9\xe0\xde\x9ccW\xca.\xb7\x12'%" +
	"s{\xed(b\xc0:w\x9b2\x19\xcbu\x87\xda*" +
	"\xe5\x82\x05\x87\xb1\xd0\xe1\xca\xcdD\xa9\xe5\x92Sk\x05" +
	"'\x98\x0d\x06\\3L\x94Z-9\xd5/x\xdc\xcc" +
	"f\x1d\xcbu9N\x82\xe3\xc4U\xd7\xb3\x1d3g=" +
	"KQkOx8\xc4\xfa#\xa9\xadg\xc0\xce\xe1\xa8" +
	"\xd5\xc1Q\xfa\x0a\xdeL\x94^\xca\x92\xd3\xab\xb9v\x9a" +
	"\xbe\x92{\x88\xd2\xcb\xc17\x82\x0ba\xb0 \xd27\xf0" +
	"*\xa2\xf4:\xf0-,\x98\xa5\xc1\x92H\xdf\xc4\xc3D" +
	"\xe9\x8d\xc0\x030\xd7\xa4\xc1\x1a\x91\xbeM\xb9\xd9\x02\x9e" +
	"\x04\x8f\xb0\xc1\x11\"}\xbb:\xb6\x1f|\x08\xbcA3" +
	"\xb8\x81HO\xf1 Q:\x09\xbe\x13<*\x0c\x15\x94" +
	"\x17\xf8\x1bD\xe9!\xf0]\xe0\xb1)\x83c\xc8o\xe5" +
	"g\x07x\x16\xbc\xf1\xa2\xc1\x8dHS\xc5w\x82\x8f\x80" +
	"7E\x0cn\"\xd2-~\x91(\x9d\x05/\xf3\xec{" +
	"\xec\xf5\xecr>3\xf3\x02\xdb\xb2\xa6g\x86W=\x8c" +
	",\xf8^\xa5H\xd1a\xcb\xe1F\x12\xdc\x88\x1f\x8e\xf5" +
	"\x9b\xeeH`4\xee\x8dm+e\xad\xb1@\xf6\x7f\xd4" +
	"o\xba\xc4\xa1MW\xbe\xdeb\xdc\xb1\x8a\xf6\xa8\x95e" +
	"&\xc1L<>\x9aw\xbc\x8aY\x08\xbeW3\xb6[" +
	"\xb4\xdd~\x93d\xed\x980\xb2\xa2g0\xd97\xe4\x98" +
	"%\xd7\xccxy\xbbD\x08\xf2\xfe0\xc8?\x90\xb8\xd5" +
	"\xb2\x94\x9c\xde'\xeb\x82\xbcG\"jc\xe0\xaf\xc9\xba" +
	" \x1f\x90\x08\xf2>\xf0C\xb2\x16\xe4\x1f\xcb\xc7\x88\xd2" +
	"\xfb\x81\xdf\x94uA~]>C\x94>\x04~\x04<" +
	"\xa2\xf9A~[\x1d\xfb\x16\xf8q\xf0\x86\x88\x1f\xe4\xa3" +
	"\x8a\xbf\x0b~\x0a<\xda\xe0\x07\xf9=u\xecq\xf03" +
	"\xe0\xb1\xa8\x1f\xe4\xd3\x12\xc1?\x09\xfe[\xf0F\xf6\x83" +
	"\xfck\xc5O\x81\x9f\x03o\x8a\xf9A>+\x17\x11\xa5" +
	"\xcf\x80O\x807\x0b\x83\x9b\x89\xf4\xf3\xf2\x0d\xa2\xf4\x04" +
	"\xf8\x14xK\xa3\xc1-D\xfa\x05\xe5\xe7\x0f\xe0\x97\xc0" +
	"\xe3\xd2\xe08\x91~Q=\xcf$\xf8\x15\xf0\xd6&\x83" +
	"[\x89\xf4\xcb\xea\xff^\x02\xbf\x0d\xde\xd6lp\x1b\x91" +
	"\xfe\x89D\xd2\xdd\x04\xbf\x03\xde\xdebp;\x91\xfe\xa9" +
	"\x9cG\x94\xbe\x05~\x17<\x1178A\xa4\x7f\xa6\xf8" +
	"m\xf0{\xe0\xf3Z\x0d\x9eG\xa4\x7f\xae\xf8\x1d\xf0/" +
	"\xa5\xe0e:\x1b\xac\xa3\xe7)\xffw\xc1\xff\x01{\xa3" +
	"\xcd`\x83H\xbf/\x91\xd4_\x82\x7f-\x05ww " +
	"\xbe\x1dD\xfaW\xf2\x03\xa2\xf4\xd7\x10b\x9a\xe0\xeeG" +
	"\x04\x1b\xfc\x08\x91\x1e\xd1\x8e\x11\xa5c\x9a\xe4\xb4\x01a" +
	"\xbed\x83\xe7\x13\xe9\x09\xed Q\xba\x1dB'\x84\x05" +
	"\x1a\x1b\xbc\x80H_\xa8\xe1\xee:!<\x0ea!*" +
	"y!\x1a\x88\x12\x1e\x87\xf0$\x84E\x0dl\xf0\"\"" +
	"\xbd[{\x99(\xbd\x16\xc2z\x08\x8fF\xd9\xe0G\xd1" +
	"V\xd5\x19\xeb l\x81\xd0\x19c\x83;\xd1D\xb4\xbd" +
	"h\"\x10\x06 ,F\xa0\x17\xa3\x8bh\xb8\xf0~\x08" +
	"C\x10\x964\xb1\xc1K\xd0.\x94\x90\x84\xb0\x13BW" +
	"3\x1b\xdc\x85~\xa1\x84\x1d\x10\xb2\x9a\x98\xb3\xfef\x14" +
	"\xf24m\xdb\xed\xd8\xc5\xe0K4g\xbaa\x09\xe7L" +
	"7\xe9\xe43\x16\x11\x85.r\xa6\xfb\x94e\xf5\x99\xc4" +
	"\xe5z6\x94/?\xc0\xdaF\xeazCW\xbeT\xae" +
	"x\xe1\xb7\x92]\xcaX\xc1!\xd2\xb3C?\xdet9" +
	"s\xde.\xa9fB\x14\x98u\x8d\x9a\x85\x8a\x15z\xf7" +
	"\xf6\x94C\x0fUSM\x15\xcb\xc5c\x86C(\\\x16" +
	"\xfc!4\x9e\x191\xf3\xa5m\xd9\xc0\x03\x8f\x86\x9f\xc2" +
	"\x8b\xe0\xb0)\xfeo\xad(x\\\x11<n\xd2\xb1\\" +
	"\xab\xe4Q\xf8\xb3\xe0\xbey\xd8r\x94(K^(\x06" +
	"\xb7\xcb\xb3~\x16\xdc1\x97\x03\xe9\x01M\xdd\xf5\\\x9a" +
	"\xba\xa3\xa4cQ\x1b\x84\x10\x07\xf73\xfb\xa0\xe9KI" +
	"R\xaf\xaf\xd4<\x85\xcek\xc6\xce\x1c\xcc\x9d\x83\xcd\xd8" +
	"\x1e\xb6[\xd23\xd1\x9c\xd7\x87\xcd\xf9\x1d5\"\xdf\xc2" +
	"H:\x8e\x89:\xdd\x9b\x8f\xaaA{\x04\xf8\xa4\x1a\xc0" +
	"\xec\xf7\xe6\x13j\x82\x1d\x07?\x03.\x85\xdf\x9cO\xab" +
	"\xc9y\x0a\xfc\\\xfd\x04>\xab&\xe7\x19\xf0\x89\xfa\x09" +
	"|^\xd9\x9f\x03\x9fT\x13X\xf8\xcd\xf9}u\xee\x04" +
	"\xf8\x94\x9a\xc0\xd2o\xce\x17\x18\x155\x09~EM`" +
	"\xcdo\xce\x97\xd5\xa4\x9d\x02\xbf\xa6&p\x93\xdf\x9c\xaf" +
	"\xaa\xe7\xbc\x02\xfe\x91\x9a\xc0\xcd~s\xbe\xa1\xec\xaf\x81" +
	"\xdf\x04o\xd6\xfc\xe6\xfc\xb1z\xce\x0f\xc1o\x81\xb7D" +
	"\xfc\xe6\xfcWF\x7f\xb9\x05~\x17<\xde\xe07\xe7\xcf" +
	"\x94\x9f\xdb\xe0\xf7Xpw\xeb~\xf6\xbb\xf3\xe7\x8c\xa6" +
	"w\x0f\xc2\xbfXp\xef\x88\x95\xcf\x8dx\x1c!\xc1\x91" +
	"\xa0\x14[Hp\x0bq\xb5l:V\xc9\x9b\xce\xe4\x00" +
	"\xba\x9e\xe9Y\x83\xb6M\xec\x05\xac\xab\x98/YNh" +
	"\xe1\xe5\x8b\x96\xeb\x99E\x94x\xe0\xd7\xcd\xef\xb5\xea{" +
	"\xc5@\xbe\x98W\x99\x10\x0c\xf8\x9c\xe9>\xe7Z\xd9\xd0" +
	"\xc6\xf2F\x86\xc6\xfa\xec\x0a\xa1\x0c4\x12\xac\xa9\xbd\xa1" +
	"\xcf\xae\xd4\xbew\x0d\x17l\xbbX;\xb7\xae%\xb8\x83" +
	"\xb6\x8dt\x9f\xd6\xc6\x87M\xd7z\xca\xb2B\xdb\xe9\xa2" +
	"\xcd\x8b\xbdV\xb6O\x15\xec\xd6Q\xab\xe4\xb9s\xa5\xe6" +
	"\x90cf\xac\xa4\xd9\xb5\xa7`\x9b\xd9\x19\xbb\xedc\xd3" +
	"\xbb\xad!8\xea\x98\xaf\xceZ=\xb8g\xd0\xcaX\xf9" +
	"\xb2Gj\xe9\x18\x08\xf3:\"z\x88\x06\x85\xe4t\x8b" +
	"\xa8\xdb9\x1a\xc5a\xa2t\x0b\xf8\x02Q\xb7st\x08" +
	"\xc4\xb3\x1d\xbcS\xd4v\x8e\x85\xf0\x926\x80\x97\xc2\x1c" +
	"\xf3\x08i\xbdX\x99/\x00_\x0e\x1e\x11~Z/\x13" +
	"H\xeb\xa5\xe0\xab\xc1\x1b\xa4\x9f\xd6+\x05\xd2z9\xf8" +
	"F\xf0\xa8\xe6\xa7\xf5\x06\x81a\xb4\x1e\xbc\x1f<\x16\xf1" +
	"\xd3z\xab\xe2[\xc0\x93\xe0\x8d\x0d~ZoW\xfe\x07" +
	"\xc0w\x807I?\xad\x9f\x13X\xa5\x86\xc0w\x89\xba" +
	"\xb4~I }w\x81\x17\xc0[\xa2~Z\xe7\xd55" +
	"\x14\xc0\xc7\xc0\xe31?\xad+\xea9\xcb\xe0\xfb\xc0[" +
	"\x1b\xfd\xac\xde#\xb0\xd3x\xe0\xfb\xc1\xdb\"\xfe\xce\xf1" +
	"#e?\x06\xfe\x9a\x10\xdc\xdd\x8e2\xc0\xd2q@8" +
	"X\xd6 \xbc\x09!q\x80\xfd\xad\xe3u\x81){\x08" +
	"\xc2\x11\x08\xf3\x0e\xb2\xbfv\xbc-\xfe\x8c\xb5\x0c\xc2)" +
	"!\xb8\x17uP\xa9\xcd\xbfL\xa5X)\x98^\x9eG" +
	"\xad\xa7U*s\xf6\xbf\xe5v\xafc\x99\xae]\x0as" +
	"s\xb4\xb8\xd5q\xecZ\xfd\x14\xec\x9c\xbb\xb9\x80\x0a\x0b" +
	"Gm\x1bXm`\x85o\xac\xd3oM\xf5\x99\x8fE" +
	"\xbb6\x823v\xc9s\xa0l\xf2Wyzp\xbe?" +
	"t\xe6\x07\x7f\xed!\xa3\xb6j\xed\xdeme\xbc\xfc(" +
	"\xe3_cD\xb15\xe7\xaeP7\xba\x1f\x1c\xc8\xfe]" +
	"$\x1d\xea\x9a1U\xfcK\x99=n\x82\x13Ep\xa2" +
	"5{\xb8\xd5\xd5\xee\xd8\xa0\xe5V\x0a\xec\xa1\xfa:\xc3" +
	"\xba\xfd=\xdeI\xcfINM\xa2\xf6\x84\xff\x0a\xf9>" +
	"\xde+'$\xa7\xa6PxR\x15^\xe2\xc23D\xa9" +
	"I\xc9\xa9+\x98&\x9a*\xbb\xc4\xe5\x17\x89R\x97$" +
	"\xa7>D\xcd\x9dT5\x97\xb8\x0e\x9fW$\xa7>B" +
	"\xc1IUp\x89\x1b\xf0yMr\xeaf\xed5.\xf1" +
	"\xf1a\xa2\xd4M\xc9\xa9;\xb3\x1ap\xf8j\x14#\xc1" +
	"1\xe2j\xd1\xcdM\xdf9\x85L\xf5\xc6m\xa5,I" +
	"k,\xe8\x85\xbd\xbb\xcd|\xa1\xee\x05if?}H" +
	"~\xd6]\xd7\x80\x9d{\xda\xb1+\\\x9e\xd1\xe6V\xd5" +
	"^\xe1\x1f\x9e\x8a\xff\x09\x00\x00\xff\xff\xc8\xa8ZH"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bc3f21e1d17a526c,
		Nodes: []uint64{
			0x8754b1c1a667a03c,
			0x8dea811504a59d2a,
			0x988b382a961e2d7b,
			0x9bbe5676024b04c9,
			0x9c1c43d8c17225f2,
			0xb40b1e0176e0c004,
			0xc136c505d60e82cc,
			0xddf9c0053b56f174,
			0xedc6ec3ead9565fa,
		},
		Compressed: true,
	})
}
